# Generated by Django 5.2.3 on 2025-06-30 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0003_submission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='language',
            field=models.CharField(choices=[('py', 'Python'), ('cpp', 'C++'), ('java', 'Java')], max_length=50),
        ),
    ]
