# Generated by Django 5.2.3 on 2025-07-04 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0004_alter_submission_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProblemTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='problem',
            name='sample_input',
            field=models.CharField(default='5 6 7 8 9', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='problem',
            name='sample_ouput',
            field=models.CharField(default='YES', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='problem',
            name='tags',
            field=models.ManyToManyField(related_name='problems', to='problems.problemtag'),
        ),
    ]
