# Generated by Django 5.2.3 on 2025-07-04 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0005_problemtag_problem_sample_input_problem_sample_ouput_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='problems', to='problems.problemtag'),
        ),
    ]
