# Generated by Django 5.2.3 on 2025-07-04 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0006_alter_problem_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='problem',
            old_name='sample_ouput',
            new_name='sample_output',
        ),
    ]
