# Generated by Django 5.2.3 on 2025-07-04 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_rank_alter_profile_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='rank',
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
